### PR TITLE
Add default value for destination id in queue-detail query

### PR DESCRIPTION
**Pull request by guerler**
The destination tag does not always seem to be available which causes problems when attempting to parse the results to influx.

### CODE REVIEW

**Comment by bgruening** [comment]
Should we not include `null` or something like that instead of dropping it. The destination might be interesting to have.

**Comment by guerler** [comment]
> Should we not include `null` or something like that instead of dropping it. The destination might be interesting to have.

Yea that would be nice, where would I add that.

**Comment by hexylena** [comment]
There's no 'null' option, either you include the column or don't. Here we should probably include it. Why are you removing it? If it's producing bad data then it might need a COALESCE statement to ensure it has some text, we use that in other places if you grep.

**Comment by bgruening** [comment]
`might need a COALESCE statement to ensure it has some text` --> `null or something like that`

**Review by hexylena — APPROVED** [review]

**Pull request merged**
