### PR TITLE
Correct whitespace and function names of a couple unrelated functions.

### PR DESCRIPTION
**Pull request by natefoo**
Also correct whitespace and function names of a couple unrelated functions.

### CODE REVIEW

**Comment by natefoo** [comment]
Oh also, 2 thoughts:

1. Should we maybe remove the group as well?
2. A "purged" flag or something on `training_trainings` would be nice so we could filter out the stuff that's already been addressed. There's no harm in running it as-is but the list of trainings will only grow.

**Review by hexylena — COMMENTED** [review]
So these could equally be commands within the tiaas codebase that would do this, and it might make automating things on that side a bit easier? it be less awkward with the switching between 2 DBs for different commands since the tiaas commands have access to both?

**Comment by hexylena** [comment]
We could make the management commands, https://docs.djangoproject.com/en/3.2/howto/custom-management-commands/ they show up when you run `python manage.py` and they could be put in a cron task easily to cleanup expired groups?

**Comment by natefoo** [comment]
Ok, I can port them over to TIaaS. Thanks for the tip!

**Comment by hexylena** [comment]
Nah you already did this, I know Django well, I can do it thanks to the
queries you've already written! And you don't have to do the same thing
twice because of my weird preferences.

Op ma 21 jun. 2021 18:41 schreef Nate Coraor ***@***.***>:

**Comment by hexylena** [comment]
xref https://github.com/usegalaxy-eu/tiaas2/pull/21

**Review by hexylena — APPROVED** [review]

**Pull request merged**
