### PR TITLE
Update the wonderful argument parser

### PR DESCRIPTION
**Pull request by hexylena**
Based on discussion in #113 to a newer specification. Now all of the following are supported:
 
```
<required>
<required|or|some|ignored|things> # Useful for <user|id|email> which is stored as arg_user
[optional]
[optional=default]
[--flag]  # Proper flag, boolean yes/undefined.
[--flag=] # No default but it's not a flag
[--flag=default] # Some default
```

This replaces the previous version of wap with some additional updates, notably these are now identical

```
--limit=123
--limit 123
```

@natefoo or @mira-miracoli would you be able to take this for a spin and check if nothing breaks that used to work?

### CODE REVIEW

**Comment by hexylena** [comment]
[WAP also now has tests](https://github.com/hexylena/wap/actions/runs/3488951641/jobs/5838423024)! So *most* of this *should* work, but, just want some real data.

**Comment by hexylena** [comment]
```
./gxadmin echoquery tool-metrics --ok --summary "Condense characters1" runtime_seconds 100
```

looks like it still didn't work

**Comment by hexylena** [comment]
precompiled if anyone wants to use it:
[gxadmin.txt](https://github.com/galaxyproject/gxadmin/files/10032597/gxadmin.txt)

**Comment by mira-miracoli** [comment]
Thank you @hexylena !
I used your code and it worked well for me :tada:

**Review by natefoo — APPROVED** [review]
Looks good to me and seems to be working in my minimal testing. I did a scan for any shell issues and didn't see anything (and you're using shellcheck anyway) so :shipit:.

> `<required|or|some|ignored|things>`

What does "ignored things" refer to here?

In addition it looks like `[--flag=<description>]` is a thing for documenting but not setting a default.

> `--help-man`

omg nroff :heart_eyes:

**Comment by hexylena** [comment]
> `<required|or|some|ignored|things>`
> What does "ignored things" refer to here?

In the case of `<a|b|c>`, only `arg_a` will be made available, not `arg_b` or `arg_c`, they serve purely as decoration/documentation for this parameter that can actually handle multiple datatypes.

> In addition it looks like [--flag=<description>] is a thing for documenting but not setting a default.

```
--flag # nada
--flag=description   # arg_flag=description
--flag=<description> # No default set
```

> omg nroff heart_eyes

:yellow_heart: i'll try and remove the pandoc dependency next and yay. proper man pages.

**Pull request merged**
